language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-dupe --allow-redirect -w quora,gamesradar,gamespew,reddit,ign,redbull,rollingstone,creativecommons,travis-ci,ghit,github
